# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametros', '0001_initial'),
        ('inmueble', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEtapa', models.CharField(max_length=45)),
                ('descripcionEtapa', models.CharField(blank=True, max_length=255, null=True)),
                ('numeroTipoInmuebleEtapa', models.IntegerField()),
                ('numeroTipoInmueble2Etapa', models.IntegerField()),
                ('tipoProyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipoProyecto', to='parametros.TipoProyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Macroproyecto',
            fields=[
                ('nombreMacroproyecto', models.CharField(max_length=45)),
                ('descripcionMacroproyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('m2Macroproyecto', models.IntegerField()),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='inmueble.Lote')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProyecto', models.CharField(max_length=255)),
                ('descripcionProyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('m2PorProyecto', models.IntegerField()),
                ('macroproyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='proyecto.Macroproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidadVentas', models.IntegerField()),
                ('porcentajeTopeRemanenteVentas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('velocidadUltimasVentas', models.IntegerField()),
                ('porcentajeTopeInicialVentas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentajeVelocidadInicialVentas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fechaInicioVentas', models.DateField()),
                ('volumenTotalVenta', models.DecimalField(decimal_places=4, max_digits=13)),
                ('reajusteVenta', models.DecimalField(decimal_places=4, max_digits=13)),
                ('volumenInicialesVenta', models.DecimalField(decimal_places=4, max_digits=13)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto', to='proyecto.Proyecto')),
            ],
        ),
    ]
