# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incremento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDeIncrementos', models.IntegerField()),
                ('porcenReajusteIncremento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcenTopeReajusteIncremento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectoIncremento', to='proyecto.Proyecto')),
                ('tipoIncremento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipoIncrementoIncr', to='parametros.TipoIncremento')),
            ],
        ),
        migrations.CreateModel(
            name='ProyeccionIPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anosProyeccionIPC', models.IntegerField()),
                ('tasaBaseProyeccionIPC', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectoProyeccion', to='proyecto.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='SubEtapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSubEtapa', models.CharField(max_length=45)),
                ('descripcionSubEtapa', models.CharField(blank=True, max_length=255, null=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapa', to='proyecto.Etapa')),
            ],
        ),
        migrations.CreateModel(
            name='TablaIPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anoTablaIPC', models.IntegerField()),
                ('ipcAnoTablaIPC', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('numeroInmueblesEntregados', models.IntegerField()),
                ('proyeccionIPC', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyeccionIPC', to='proyecto.ProyeccionIPC')),
            ],
        ),
        migrations.AlterField(
            model_name='venta',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectoVenta', to='proyecto.Proyecto'),
        ),
    ]
