# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20171102_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='reajusteVenta',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='volumenInicialesVenta',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='volumenTotalVenta',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
