# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20171107_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incremento',
            name='porcenReajusteIncremento',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
