# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20171216_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='macroproyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='macroproyecto', to='proyecto.Macroproyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombreProyecto',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
