# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20171217_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nombreProyecto',
            field=models.CharField(max_length=255),
        ),
    ]
