# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_auto_20171216_2224'),
        ('proyecto', '0007_auto_20171218_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incremento',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='incremento',
            name='tipoIncremento',
        ),
        migrations.AddField(
            model_name='venta',
            name='numeroDeIncrementos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='porcenReajusteIncremento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='porcenTopeReajusteIncremento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipoIncremento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tipoIncrementoIncr', to='parametros.TipoIncremento'),
        ),
        migrations.DeleteModel(
            name='Incremento',
        ),
    ]
