# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_auto_20180117_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='volumenTotalVenta',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
