# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_auto_20180124_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='proyectoEtapa',
            field=models.ForeignKey(default=999999999, on_delete=django.db.models.deletion.PROTECT, related_name='etapas_proyecto', to='proyecto.Proyecto'),
        ),
    ]
