# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_etapa_proyectoetapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='tipoProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapas_tipoproy', to='parametros.TipoProyecto'),
        ),
    ]
