# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0012_auto_20180124_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='tipoProyecto',
        ),
    ]
