# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0003_auto_20171216_2224'),
        ('proyecto', '0013_remove_etapa_tipoproyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='tipoProyecto',
            field=models.ForeignKey(default=999999999, on_delete=django.db.models.deletion.PROTECT, related_name='etapa_tipoproy', to='parametros.TipoProyecto'),
        ),
    ]
