# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_etapa_tipoproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='reajusteVenta',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='volumenInicialesVenta',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
