# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-13 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_auto_20180204_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='numeroTipoInmueble2Etapa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='numeroTipoInmuebleEtapa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
