# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-05 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_auto_20180213_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='tipoProyecto',
        ),
    ]
