# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-06 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0017_remove_etapa_tipoproyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='proyecto',
        ),
    ]
