# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-06 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0018_remove_venta_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='subetapa',
            field=models.ForeignKey(default=999999999, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='proyecto.SubEtapa'),
        ),
    ]
