# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-08 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0019_venta_subetapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyeccionipc',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='proyeccionipc',
            name='subetapa',
            field=models.ForeignKey(default=999999999, on_delete=django.db.models.deletion.PROTECT, related_name='proyeccionIPC', to='proyecto.SubEtapa'),
        ),
    ]
