# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-02 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0020_auto_20180508_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='descripcionEtapa',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='nombreEtapa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='macroproyecto',
            name='descripcionMacroproyecto',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='macroproyecto',
            name='nombreMacroproyecto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcionProyecto',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subetapa',
            name='descripcionSubEtapa',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='subetapa',
            name='nombreSubEtapa',
            field=models.CharField(max_length=255),
        ),
    ]
