# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreParametro', models.CharField(max_length=45)),
                ('descripcionParametro', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoIncremento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoIncremento', models.IntegerField()),
                ('valorIncrementoTipoIncremento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoProyecto', models.CharField(max_length=45)),
                ('descripcionTipoProyecto', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
