# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoincremento',
            name='descripcionTipoIncr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
