# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_tipoincremento_descripciontipoincr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoincremento',
            name='valorIncrementoTipoIncremento',
        ),
        migrations.AddField(
            model_name='tipoincremento',
            name='nombreIncrementoTipoIncremento',
            field=models.CharField(default='Incremento', max_length=50),
        ),
    ]
