# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaBrutaLote', models.DecimalField(decimal_places=3, max_digits=8)),
                ('areaCesionViasLote', models.DecimalField(decimal_places=3, max_digits=8)),
                ('porcentajeCesionVerdesLote', models.DecimalField(decimal_places=2, max_digits=5)),
                ('areaCesionTierraLote', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valorM2Cesion', models.DecimalField(decimal_places=4, max_digits=13)),
                ('valorLote', models.DecimalField(decimal_places=4, max_digits=13)),
                ('valorPorcentajeLote', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentajeFinanciarLote', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mesesGraciaInteresesLote', models.IntegerField()),
                ('tasaInteresMensualLote', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mesesTotalesPagoLote', models.IntegerField()),
                ('valorTotalLote', models.DecimalField(decimal_places=4, max_digits=13)),
                ('mesesDePagoLote', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PagoLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesPagoLote', models.IntegerField()),
                ('porcentajeMesPagoLote', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ParametroInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreParametroInmueble', models.CharField(max_length=45)),
                ('valorParametroInmueble', models.CharField(max_length=45)),
                ('descripcionParametro', models.CharField(blank=True, max_length=255, null=True)),
                ('m2MinimoParametroInmueble', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaTipoInmueble', models.IntegerField()),
                ('noUnidadesTipoInmueble', models.IntegerField()),
                ('valorM2TipoInmueble', models.DecimalField(decimal_places=4, max_digits=13)),
                ('secundarioTipoInmueble', models.BooleanField()),
                ('valorSalariosMinTipoInmueble', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
