# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0004_auto_20171108_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='nombreLote',
            field=models.CharField(default='Pepito', max_length=50),
            preserve_default=False,
        ),
    ]
