# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0005_lote_nombrelote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='nombreLote',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
