# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0006_auto_20171109_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoinmueble',
            name='nombreTipoInmueble',
            field=models.CharField(default='tipoDef', max_length=45, unique=True),
            preserve_default=False,
        ),
    ]
