# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0009_auto_20171212_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='valorEnPorcentaje',
            field=models.BooleanField(default=False),
        ),
    ]
