# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0010_lote_valorenporcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoinmueble',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipoInmueble', to='proyecto.Etapa'),
        ),
        migrations.AlterField(
            model_name='tipoinmueble',
            name='paramInmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipoInmueble', to='inmueble.ParametroInmueble'),
        ),
    ]
