# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-04 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0011_auto_20180124_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoinmueble',
            name='valorSalariosMinTipoInmueble',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
