# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-06 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0017_remove_etapa_tipoproyecto'),
        ('inmueble', '0012_auto_20180304_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoinmueble',
            name='etapa',
        ),
        migrations.AddField(
            model_name='tipoinmueble',
            name='subEtapa',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.PROTECT, related_name='tipoInmueble', to='proyecto.SubEtapa'),
            preserve_default=False,
        ),
    ]
