# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmueble', '0013_auto_20180506_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoinmueble',
            name='nombreTipoInmueble',
            field=models.CharField(max_length=45),
        ),
    ]
